CREATE TABLE `nabhackthon`.`customer_master` (
  `CUSTOMERID` VARCHAR(50) NOT NULL,
  `CUSTOMERNAME` VARCHAR(50) NOT NULL,
  PRIMARY KEY (`CUSTOMERID`),
  UNIQUE INDEX `CUSTOMERID_UNIQUE` (`CUSTOMERID` ASC) VISIBLE)
COMMENT = 'Customer master';